// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knupafptriagmodxbmsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudXBhZnB0cmlhZ21vZHhibXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MjExOTYsImV4cCI6MjA1MzQ5NzE5Nn0.3vIgXJVGRcdVGVgcp4X6HNNiwM2OBDXOvI-_Ucf6ffo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});